[package]
name = "warp"
version = "0.1.0"
authors = ["cpowicki <chpowicki@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"